### ISSUE TITLE
make licensing more welcoming?

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses.io#11]
I had an email exchange with an Austrian OSM user who thought OA only accepted CC0 datasets. I clarified that we have a ton of CC-BY. But I wonder if this is scaring off governments? 

Opening this ticket to collect thoughts on how/if we can make this situation clearer.

**Comment by iandees** [comment]
We should definitely make it clearer. Our principal should be that we collect _all_ address datasets, with a strong preference for CC0 or CC-BY.

We're probably running into name collisions with the existing (but dormant) OpenAddresses project and with OpenStreetMap (which basically can only accept CC0).

**Comment by migurski** [comment]
I think it might be possible to close this issue now. With differently-licensed downloads on http://results.openaddresses.io and explicit license information in the downloadable collections and [called out in the contribution guide](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-tags), I think we’re making good progress!
