### ISSUE TITLE
estimate of population coverage

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses.io#14]
I spent a little time today looking up population counts for covered areas. Here's what I've got so far (if anyone wants edit access, lmk):

https://docs.google.com/spreadsheets/d/1x814db9sFEPRmGW1CvMsyhg12CScib-pJ6K3xTqdydA/edit?usp=sharing

You can see a graph of the relationship between addresses and population size here:

![image](https://cloud.githubusercontent.com/assets/31717/5401339/8ea17b2c-8148-11e4-9b82-1a64c259569a.png)
https://docs.google.com/spreadsheets/d/1x814db9sFEPRmGW1CvMsyhg12CScib-pJ6K3xTqdydA/pubchart?oid=1618183979&format=image

Notes:
- Japan is excluded, because we have block points, not address points, for it -- apples & oranges.
- Seoul is treated as a separate data series, simply to give a cleaner trend line. It seems that there are fewer addresses per person than in our other sources, which are overwhelmingly western. It will be interesting to see if regional patterns emerge as we collect more data. For now, I'm using the mostly-western trend line, which means our estimates will likely be undercounts.
- A bug related to trendlines in Google Sheets forced me to take the logarithm of the input data prior to graphing it -- don't use those coefficients raw. The actual formula for raw data is `2.028x + 10395.349`. If we simplify that to `2x + 10400`, then 

**OpenAddresses' current (non-Japan) total of 59,224,955 addresses implies coverage for 118+ million people. If you decide to add Japan, that number doubles.**

Not bad! (Though I should note that these numbers reflect some not-yet-merged PRs.)

This might be a nice thing to keep track of on the home page eventually. More importantly, it should give us a rough proxy for the ballpark number of addresses in a jurisdiction. We're definitely missing data for several jurisdictions thanks to a [bug affecting ESRI data sources](https://github.com/openaddresses/openaddresses-conform/issues/35).

**Comment by waldoj** [comment]
Very encouraging! Thanks for doing the math in that. This should be a counter on the project homepage. (He said, making no effort to make that happen.)

**Comment by migurski** [comment]
I’ve followed up on this here: http://mike.teczno.com/notes/openaddr/population-comparison.html

Since this issue is over a year old, I’m going to close it. I think we should definitely continue on this. I’m going to try to talk with Mikel about it sometime this week, to see what kind of regular report or display we might add to the OA page with this information.
