### ISSUE TITLE
Is this really just a demo?

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses.io#18]
If this is live, we shouldn't call it a demo. If it's just a demo, it shouldn't be live for everyone.

![screen shot 2014-12-18 at 11 04 24 am](https://cloud.githubusercontent.com/assets/98233/5491345/420762be-86a6-11e4-8ae0-9f463a78b23c.png)

**Comment by ingalls** [comment]
The contributing panel is now fully functioning.
