### ISSUE TITLE
Integrate data.oa.io into design

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses.io#19]
http://data.openaddresses.io/runs/1418584913.103/index.html

![](https://s3.amazonaws.com/f.cl.ly/items/081E440c470E3J3V0f1u/oa.gif)

**Comment by lxbarth** [comment]
There's also some conceptual overlap with contribute/ - not sure how to reconcile.

**Comment by ingalls** [comment]
@lxbarth `data` is more of a raw overview of the current contribute code. It show errors at a much lower level than that of the contribute page. I'll be hooking some of this data into the `contributing` section using the `status.json` see https://github.com/openaddresses/machine/issues/14

**Comment by ingalls** [comment]
<img width="1061" alt="screen shot 2015-08-27 at 9 54 46 am" src="https://cloud.githubusercontent.com/assets/1297009/9522256/db9f9600-4ca1-11e5-94aa-dbf092e8ace8.png">

Done!
