### ISSUE TITLE
Add awesome map

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses.io#2]
Courtesy @aaronlidman - http://bl.ocks.org/aaronlidman/raw/2c2a45ab797e01514db2/

The map goes a long way to show coverage and to encourage contribution. I'd just stick this at the bottom of the current site.

@aaronlidman - how hard is it to update the map?

/cc @ericfischer @ingalls @iandees

**Comment by aaronlidman** [comment]
Yep https://github.com/openaddresses/map

@lxbarth Not too hard but could be improved, takes ~2 hours. If going past zoom ~12 it should be run on a server with many cores.

I'm currently rendering out another version with updated data and some style tweaks.

**Comment by ingalls** [comment]
@lxbarth I'll get it added to the site.
