### ISSUE TITLE
update map, darken points on style

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses.io#49]
@tristen what do you think about darkening the points for high zoom levels? things currently go from really clear contours like

![image](https://cloud.githubusercontent.com/assets/31717/7419275/089d197e-ef42-11e4-8927-26f23f4abeb5.png)

to this, where the boundaries are much harder to see

![image](https://cloud.githubusercontent.com/assets/31717/7419256/f31c9d7c-ef41-11e4-872b-2b20b7d5c7d7.png)

what do you think? happy to be told this is a dumb idea if you think it is

**Comment by tristen** [comment]
This is a good idea - there should be a clear contrast at this zoom level.

**Comment by sbma44** [comment]
Cool. Can you update or point me to the style?

**Comment by tristen** [comment]
Map is here: https://github.com/openaddresses/openaddresses.io/tree/gh-pages/_src/openaddresses.tm2

cc @kelvinabrokwa

**Comment by sbma44** [comment]
OK, updated the ticket -- might as well regenerate the mbtiles at the same time. Not sure if I or @kelvinabrokwa will be a likelier candidate to grab this in the short term.

**Comment by kelvinabrokwa** [comment]
@sbma44 I got it. I'll let you look at the style out before I regenerate.

**Comment by sbma44** [comment]
@kelvinabrokwa you are a gentleman and a scholar

**Comment by kelvinabrokwa** [comment]
Closing per [7701da9847dd6e](https://github.com/openaddresses/openaddresses.io/commit/7701da9847dd6eb132d0ca34e1de4d4385cd4511)
