### ISSUE TITLE
Exaggerated permissions via GitHub account

### ISSUE THREAD

**Issue by alexandre-mbm** [openaddresses/openaddresses.io#51]
I access [openaddresses.io/login](http://openaddresses.io/login/) and see:

![openadresses io github](https://cloud.githubusercontent.com/assets/957501/8392149/99a4364a-1cb6-11e5-9177-390cab28ebe5.png)

This is inappropriate.

For what you need so much power?

**Comment by iandees** [comment]
Github doesn't allow us to scope our requests any narrower than "write to all public repository data". If you don't trust us, you can view our code to confirm we're not doing anything nefarious or just open a ticket describing the data source.

**Comment by alexandre-mbm** [comment]
For me viewing the code is not enough. It can change or you can commit unintentional errors. But I understand the issue and I accept the suggestion to open tickets.
