### ISSUE TITLE
Suggestion: link to CONTRIBUTING.md before sign in

### ISSUE THREAD

**Issue by wilsaj** [openaddresses/openaddresses.io#53]
Some people (myself included) might not be super comfortable granting the github permissions required for the "submit a dataset" app: read/write access to all of public repos associated with an account (including organizations). I think the PR route described in the [contributing.md](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md) is just dandy. However this link only shows up _after_ having done the github auth dance. It would be better if this was linked to prior to github sign in.

Maybe just add a link from the login modal?

**Comment by migurski** [comment]
I think we’re moving toward removing the sign in process entirely in https://github.com/openaddresses/openaddresses.io/issues/62.

**Comment by iandees** [comment]
Fixed in #63.

**Comment by migurski** [comment]
Login feature is now removed as of https://github.com/openaddresses/openaddresses.io/pull/63.
