### ISSUE TITLE
Put site behind HTTPS

### ISSUE THREAD

**Issue by waldoj** [openaddresses/openaddresses.io#59]
Could we put openaddresses.io, data.openaddresses.io, and results.openaddresses.io behind HTTPS? The simplest way to do that (and, really, only way to do that under the present hosting arrangement) would be with a free CloudFlare account. That provides incomplete HTTPS, but it's a heck of a good start.

([Here's some background](https://usopendata.org/2015/11/18/https/) on why this is worth doing.)

**Comment by migurski** [comment]
Still a good idea.

**Comment by iandees** [comment]
openaddresses.io is behind Cloudflare's free SSL thing, but results.openaddresses.io is not. If we can throw an ELB in front of it we can use Amazon's free SSL thing to make that happen.

**Comment by migurski** [comment]
I would be into helping with that. Results.openaddresses.io is currently a simple Apache proxy in front of a Gunicorn app.

**Comment by iandees** [comment]
We did this! Yayyy!

This was way easier than I thought it would be because I remembered that the whole `openaddresses.io` domain is under Cloudflare and we had bypassed it for `results.openaddresses.io`. I removed that bypass and now we're SSL!
