### ISSUE TITLE
Malformed Data Files

### ISSUE THREAD

**Issue by sjsteve08** [openaddresses/openaddresses.io#78]
I've downloaded all the CSV/VRT files for the USA b region, extracted it all and began ingesting it. I've noticed a lot of malformed files making it a PIA to ingest. For example, in AK file fairbanks_north_star_borough.csv the postal code is 1 column off in the whole file:
LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID,HASH
-147.6900401,64.810945,2058,LAKEVIEW TERRACE 2 RD,,,,,,40973,c13c4ce87e21c2dc

In 50+ other files records wrap to the next line and have duplicate values like they weren't generated right.

Does anyone else have these issues? Is there a utility to ingest these files which "fixes" all these issues?

**Comment by iandees** [comment]
In the example you give, the `40973` is the value of the `ID` column, not the postcode:

![image](https://user-images.githubusercontent.com/261584/67682126-ae69fd80-f95c-11e9-9493-2e4b0073b6f6.png)

Can you give more specific examples of errors you're seeing in the other files?

**Comment by sjsteve08** [comment]
You're right about the AK postcodes, my first instinct was it's off by a column. I guess that's right buy why no postcode then? 
Here are some formatting issues. The file followed by sample line #'s. I included some snippets of sample data. The NV henderson.csv file had thousands of issues.

us\al\limestone.csv
30025
30026
![ak_30025](https://user-images.githubusercontent.com/28401921/67724251-ce2d1000-f9b4-11e9-9682-516bd378d5c1.PNG)


us\ca\city_of_huntington_beach.csv
55175
55176
![ca_55175](https://user-images.githubusercontent.com/28401921/67724269-e6049400-f9b4-11e9-864b-667dae452d4a.PNG)
78637
78638
![ca_78637](https://user-images.githubusercontent.com/28401921/67724260-dab16880-f9b4-11e9-84ab-3ccb9897083d.PNG)

us\ca\city_of_redlands.csv
24793
24794
24795
24796
24797
us\ca\city_of_santa_clara.csv
33461
33462
us\ca\santa_clara.csv
321683
321684
us\ca\ventura.csv
13550
13551
50708
50709
96375
us\co\city_of_vail.csv
8779
8780
us\de\kent.csv
47380
47381
us\fl\city_of_gainesville.csv
37285
37286
71303
71304
us\fl\hillsborough.csv
562490
562491
564285
564286
599024
us\fl\palm_beach_county.csv
234386
234387
622919
622920
629979
us\fl\sarasota.csv
48858
48859
us\hi\kauai.csv
23595
23596
us\il\shelby.csv
4901
4902
4932
4933
5021
us\il\woodford.csv
8885
8886
8931
8932
us\in\statewide.csv
1560847
1560848
1704864
1704865
1742905
us\la\red_river_parish.csv
2571
2572
us\ma\statewide.csv
1154980
1154981
1322774
1322775
2305413
us\mn\anoka.csv
436
437
us\mn\lake.csv
8229
8230
us\mn\steele_urban.csv
12172
12173
us\ms\city_of_diamondhead.csv
1469
1470
us\ms\hancock.csv
13452
13453
us\nd\stutsman.csv
1996
1997
us\nj\bergen.csv
65055
65056
us\nm\city_of_santa_fe.csv
36243
36244
us\nm\taos.csv
8196
8197
us\nv\henderson.csv
89
90
91
92
93
![nv_henderson](https://user-images.githubusercontent.com/28401921/67724291-f3ba1980-f9b4-11e9-8a5b-b4af0fda7278.PNG)

us\ny\statewide.csv
2743561
2743562
3050499
3050500
3233298
us\oh\muskingum.csv
40282
40283
us\ok\city_of_midwest_city.csv
29237
29238
us\pa\northampton.csv
88661
88662
us\pa\tioga.csv
11329
11330
us\ut\city_of_morgan.csv
1050
1051
us\va\henrico.csv
126308
126309
us\wa\pierce.csv
302602
302603
375884
375885
381836
us\wi\milwaukee.csv
325067
325068
334728
334729
us\wi\statewide.csv
2244560
2244561
2244562
2244563


-86.8572929,34.8358988,26082,MEADOW RIDGE LN,,ATHENS,,,35613,,b2a359a53e26ec2d
-86.8577703,34.8031102,26083,NICK DAVIS RD,"L
L",ATHENS,,,35613,,6325c1dabc4ff10c
-86.8576301,34.7737642,26084,CAPSHAW RD,,ATHENS,,,35613,,342de5fe7ff846b3

**Comment by iandees** [comment]
> I guess that's right buy why no postcode then?

Not all sources have postcode information in their datasets.

> Here are some formatting issues...

It's valid for fields in CSVs to have newlines in them. That's why there are double-quotes around those fields. Make sure you're using a proper CSV parser that can handle these.

Having said that, addresses shouldn't have newlines in them. Since these are spread across many data sources, it's likely that the sources have bad data in them. I would suggest filtering out addresses with crummy data like this.

**Comment by ingalls** [comment]
Going to close this issue. If folks are still having issues, feel free to open a ticket in our main data repo https://github.com/openaddresses/openaddresses
