### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by joao** [openaddresses/openaddresses.io#9]
The website won't work with www as a subdomain: www.openaddresses.io
You should probably add a DNS entry for the subdomain to redirect to the naked domain.

**Comment by migurski** [comment]
Huh, good catch. I’ll figure out who does the DNS. @iandees? @ingalls?

**Comment by iandees** [comment]
Who types www anymore?! :)

I can add a CNAME+redir bucket for sure.
​

**Comment by ingalls** [comment]
@iandees is this just a matter of updating: https://github.com/openaddresses/openaddresses.io/blob/gh-pages/CNAME or does this need to be done at your end with the Domain provider?

**Comment by iandees** [comment]
I need to add the www as a CNAME.

**Comment by harry-wood** [comment]
"Who types www any more?" 

....well whoever set the website of the organisation on github for a start! ( https://github.com/openaddresses )

**Comment by ingalls** [comment]
Hey @harry-wood thanks for noticing that, I've updated it.

**Comment by iandees** [comment]
www.openaddresses.io now redirects to openaddresses.io.
